version: '3.8'

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: sejm-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt

  postgres:
    image: postgres:15-alpine
    container_name: sejm-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-parliament_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: sejm-keycloak
    restart: always
    command: [ "start-dev", "--proxy=edge", "--http-relative-path=/auth" ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/parliament_db
      KC_DB_USERNAME: ${DB_USER:-admin}
      KC_DB_PASSWORD: ${DB_PASS:-password}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASS:-admin}
      KC_HOSTNAME: sejm-insight.duckdns.org
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "true"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: sejm-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@sejm.pl}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_REVERSE_PROXY_AUTHENTICATION: 'True'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: sejm-backend
    restart: on-failure
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-parliament_db}
      DB_USER: ${DB_USER:-admin}
      DB_PASS: ${DB_PASS:-password}
      KC_SERVER_URL: https://sejm-insight.duckdns.org/auth
      KC_ISSUER_URL: https://sejm-insight.duckdns.org/auth/realms/parliament-realm
      SERVER_SERVLET_CONTEXT_PATH: /api
      SERVER_FORWARD_HEADERS_STRATEGY: native
    depends_on:
      - postgres
      - keycloak

  portainer:
    image: portainer/portainer-ce:latest
    container_name: sejm-portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  postgres_data:
  portainer_data: