spring:
  application:
    name: SejmInsight

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:parliament_db}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 25
          order_inserts: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URL:http://localhost:8081/realms/parliament-realm}

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

parliament:
  url: ${SEJM_API_URL:https://api.sejm.gov.pl/sejm/}
  term: ${SEJM_API_TERM:term10/MP}
  auth:
    server-url: ${KC_SERVER_URL:http://localhost:8081}
    realm: ${KC_REALM:parliament-realm}
    admin:
      client-id: ${KC_ADMIN_CLIENT_ID:parliament-admin-client}
      client-secret: ${KC_ADMIN_CLIENT_SECRET:your_secret_here}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.parliament: DEBUG
