spring:
  application:
    name: SejmInsight

  datasource:
    url: jdbc:postgresql://${DB_HOST:sejm-postgres}:${DB_PORT:5432}/${DB_NAME:parliament_db}
    username: ${DB_USER:sejm_user}
    password: ${DB_PASS:P4ss_Postgr12}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 25
          order_inserts: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/iam
      - classpath:db/migration/deputy
      - classpath:db/migration/comments
      - classpath:db/migration/voting

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URL:https://sejm-insight.duckdns.org/auth/realms/parliament-realm}

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native

parliament:
  url: ${SEJM_API_URL:https://api.sejm.gov.pl/sejm/}
  term: ${SEJM_API_TERM:term10}
  iam:
    keycloak:
      server-url: ${KC_SERVER_URL:https://sejm-insight.duckdns.org/auth}
      realm: ${KC_REALM:parliament-realm}
      admin-client-id: ${KC_ADMIN_CLIENT_ID:parliament-admin-client}
      admin-client-secret: ${KC_ADMIN_CLIENT_SECRET:TUTAJ_WKLEJ_SECRET_Z_KEYCLOAKA}

openai:
  api-key: ${OPENAI_API_KEY:}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.parliament: DEBUG

app:
  cors:
    allowed-origins: "https://sejm-insight.duckdns.org,http://localhost:5173,http://127.0.0.1:5173"