/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as AppLayoutIndexRouteImport } from './routes/_app-layout/index'
import { Route as AuthLayoutLoginRouteImport } from './routes/_auth-layout/login'
import { Route as AppLayoutProfileRouteImport } from './routes/_app-layout/profile'
import { Route as AppLayoutAboutRouteImport } from './routes/_app-layout/about'
import { Route as AppLayoutDeputiesIndexRouteImport } from './routes/_app-layout/deputies/index'
import { Route as AppLayoutDebatesIndexRouteImport } from './routes/_app-layout/debates/index'
import { Route as AppLayoutDeputiesDeputyIdRouteImport } from './routes/_app-layout/deputies/$deputyId'
import { Route as AppLayoutDebatesDebateIdRouteImport } from './routes/_app-layout/debates/$debateId'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppLayoutProfileRoute = AppLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutAboutRoute = AppLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutDeputiesIndexRoute = AppLayoutDeputiesIndexRouteImport.update({
  id: '/deputies/',
  path: '/deputies/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutDebatesIndexRoute = AppLayoutDebatesIndexRouteImport.update({
  id: '/debates/',
  path: '/debates/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutDeputiesDeputyIdRoute =
  AppLayoutDeputiesDeputyIdRouteImport.update({
    id: '/deputies/$deputyId',
    path: '/deputies/$deputyId',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutDebatesDebateIdRoute =
  AppLayoutDebatesDebateIdRouteImport.update({
    id: '/debates/$debateId',
    path: '/debates/$debateId',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/about': typeof AppLayoutAboutRoute
  '/profile': typeof AppLayoutProfileRoute
  '/login': typeof AuthLayoutLoginRoute
  '/debates/$debateId': typeof AppLayoutDebatesDebateIdRoute
  '/deputies/$deputyId': typeof AppLayoutDeputiesDeputyIdRoute
  '/debates/': typeof AppLayoutDebatesIndexRoute
  '/deputies/': typeof AppLayoutDeputiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
  '/about': typeof AppLayoutAboutRoute
  '/profile': typeof AppLayoutProfileRoute
  '/login': typeof AuthLayoutLoginRoute
  '/debates/$debateId': typeof AppLayoutDebatesDebateIdRoute
  '/deputies/$deputyId': typeof AppLayoutDeputiesDeputyIdRoute
  '/debates': typeof AppLayoutDebatesIndexRoute
  '/deputies': typeof AppLayoutDeputiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_app-layout/about': typeof AppLayoutAboutRoute
  '/_app-layout/profile': typeof AppLayoutProfileRoute
  '/_auth-layout/login': typeof AuthLayoutLoginRoute
  '/_app-layout/': typeof AppLayoutIndexRoute
  '/_app-layout/debates/$debateId': typeof AppLayoutDebatesDebateIdRoute
  '/_app-layout/deputies/$deputyId': typeof AppLayoutDeputiesDeputyIdRoute
  '/_app-layout/debates/': typeof AppLayoutDebatesIndexRoute
  '/_app-layout/deputies/': typeof AppLayoutDeputiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile'
    | '/login'
    | '/debates/$debateId'
    | '/deputies/$deputyId'
    | '/debates/'
    | '/deputies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/login'
    | '/debates/$debateId'
    | '/deputies/$deputyId'
    | '/debates'
    | '/deputies'
  id:
    | '__root__'
    | '/_app-layout'
    | '/_auth-layout'
    | '/_app-layout/about'
    | '/_app-layout/profile'
    | '/_auth-layout/login'
    | '/_app-layout/'
    | '/_app-layout/debates/$debateId'
    | '/_app-layout/deputies/$deputyId'
    | '/_app-layout/debates/'
    | '/_app-layout/deputies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/': {
      id: '/_app-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth-layout/login': {
      id: '/_auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app-layout/profile': {
      id: '/_app-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppLayoutProfileRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/about': {
      id: '/_app-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppLayoutAboutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/deputies/': {
      id: '/_app-layout/deputies/'
      path: '/deputies'
      fullPath: '/deputies/'
      preLoaderRoute: typeof AppLayoutDeputiesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/debates/': {
      id: '/_app-layout/debates/'
      path: '/debates'
      fullPath: '/debates/'
      preLoaderRoute: typeof AppLayoutDebatesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/deputies/$deputyId': {
      id: '/_app-layout/deputies/$deputyId'
      path: '/deputies/$deputyId'
      fullPath: '/deputies/$deputyId'
      preLoaderRoute: typeof AppLayoutDeputiesDeputyIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/debates/$debateId': {
      id: '/_app-layout/debates/$debateId'
      path: '/debates/$debateId'
      fullPath: '/debates/$debateId'
      preLoaderRoute: typeof AppLayoutDebatesDebateIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutAboutRoute: typeof AppLayoutAboutRoute
  AppLayoutProfileRoute: typeof AppLayoutProfileRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutDebatesDebateIdRoute: typeof AppLayoutDebatesDebateIdRoute
  AppLayoutDeputiesDeputyIdRoute: typeof AppLayoutDeputiesDeputyIdRoute
  AppLayoutDebatesIndexRoute: typeof AppLayoutDebatesIndexRoute
  AppLayoutDeputiesIndexRoute: typeof AppLayoutDeputiesIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutAboutRoute: AppLayoutAboutRoute,
  AppLayoutProfileRoute: AppLayoutProfileRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutDebatesDebateIdRoute: AppLayoutDebatesDebateIdRoute,
  AppLayoutDeputiesDeputyIdRoute: AppLayoutDeputiesDeputyIdRoute,
  AppLayoutDebatesIndexRoute: AppLayoutDebatesIndexRoute,
  AppLayoutDeputiesIndexRoute: AppLayoutDeputiesIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
