/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SilentCallbackRouteImport } from './routes/silent-callback'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SilentCallbackRoute = SilentCallbackRouteImport.update({
  id: '/silent-callback',
  path: '/silent-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/silent-callback': typeof SilentCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/silent-callback': typeof SilentCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/silent-callback': typeof SilentCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/login'
    | '/profile'
    | '/silent-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/callback' | '/login' | '/profile' | '/silent-callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/callback'
    | '/login'
    | '/profile'
    | '/silent-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SilentCallbackRoute: typeof SilentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/silent-callback': {
      id: '/silent-callback'
      path: '/silent-callback'
      fullPath: '/silent-callback'
      preLoaderRoute: typeof SilentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SilentCallbackRoute: SilentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
